title: Kashav Madan
email: kshvmdn@gmail.com
description: Kashav Madan (@kshvmdn), personal website &amp; portfolio. Software developer &amp; open source enthusiast.
exclude: [
  '.gitignore',
  'CNAME',
  'LICENSE',
  'README.md'
]
